### ISSUE TITLE
多言語対応で翻訳ができていない箇所がある

### ISSUE THREAD

**Issue by yoshikos** [covid19-tochigi/covid19#11]
## 改善詳細 / Details of Improvement
多言語未対応部分
①サイトタイトルの「栃木県内の最新感染動向」の文言
②陽性患者の属性の居住地の各データ
③グラフタイトル「新型コロナウイルス感染症に関する電話相談件数」の文言

## スクリーンショット / Screenshot
①サイトタイトルの「栃木県内の最新感染動向」の文言
![image](https://user-images.githubusercontent.com/61943978/78344256-180ac980-75d7-11ea-84de-94ca2582e1b0.png)

②陽性患者の属性の居住地の各データ
![image](https://user-images.githubusercontent.com/61943978/78344291-248f2200-75d7-11ea-99eb-c8b89596db40.png)

③グラフタイトル「新型コロナウイルス感染症に関する電話相談件数」の文言
![image](https://user-images.githubusercontent.com/61943978/78344316-2eb12080-75d7-11ea-9f25-d9f58508c84e.png)

## 期待する見せ方・挙動 / Expected behavior
各対応言語に翻訳して表示する

## 動作環境・ブラウザ / Environment
-  Windows /  iOS 
- Chrome / Safari /  Internet Explorer

**Comment by y-ishida** [comment]
#12 マージしましたが、②陽性患者の属性の居住地の各データ の一部の翻訳が反映されていませんね。もしかして、data/data.json にも手を加えていましたか？　data/data.jsonを除いてマージしてしまった影響かも。

**Comment by toson77** [comment]
data.jsonは変更してなかったようですが、陽性患者の属性の居住地の各データ の翻訳自体に見落としがあったようなので、再度プルリク出します。

**Comment by yoshikos** [comment]
4月15日1：44現在ですが、
本番環境のサイトを確認しましたところ、
各言語の陽性患者数の属性の居住地　と、
韓国語では、それ以外の部分でも、翻訳がまだらになっているようです。
みなさんも、この現象、再現してますでしょうか？
![image](https://user-images.githubusercontent.com/61943978/79251867-b6423d80-7ebb-11ea-9660-83548c73af07.png)

**Comment by y-ishida** [comment]
ありがとうございます。再現します。
他言語も翻訳がまだら、またはおかしい箇所がありますね。例えば、左ペインの「知事からのメッセージ」が英語だと「Message from Governor Koike on COVID-19」となっていて小池都知事からのメッセージに見えます。多言語対応の対応はどうしていくか悩みどころですが、とりあえず再オープンしておきます。

**Comment by y-ishida** [comment]
プルリク #38 をマージした勢いでクローズされてしまったので再オープン。 #38 によって一部修正されました。
