### ISSUE TITLE
トップページのロゴにより栃木県公式に思われてしまう可能性あり

### ISSUE THREAD

**Issue by y-ishida** [covid19-tochigi/covid19#2]
## 改善詳細 / Details of Improvement
- トップページのロゴが栃木県のロゴなので、公式に思われてしまう可能性がある
- 他の非公式サイトを参考にロゴを変更したほうが良さそう

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/836976/77839484-0cbf3480-71b8-11ea-837e-bca4f9487a32.png)

## 期待する見せ方・挙動 / Expected behavior
- https://stopcovid19-gunma.netlify.com/ とか https://fukushima-covid19.firebaseapp.com/ のように、公式でないサイトは県の形？をロゴに入れるのが定番のよう

**Comment by KToshie** [comment]
hagume　さんが作っていただいたOGPそのままロゴとして使えるかと思いますが、どうでしょう？

https://www.dropbox.com/s/uim4kh28okyg1jm/logo.png?dl=0

**Comment by hagume** [comment]
KToshieさん、ありがとうございます。
少しだけロゴを加工して、ローカル環境でデプロイしてみました。悪くないと思います。
<img width="632" alt="イメージ" src="https://user-images.githubusercontent.com/62798392/78041086-473cf300-73ab-11ea-9902-eaccebe75f39.png">

**Comment by y-ishida** [comment]
ありがとうございます！
@hagume さん、プルリク出して頂けますか？
