### ISSUE TITLE
iOSのfaviconが東京都のままになっている

### ISSUE THREAD

**Issue by y-ishida** [covid19-tochigi/covid19#37]
## 起こっている問題 / The Problem
- iOSでお気に入り登録すると東京都のアイコンが表示される

## スクリーンショット / Screenshot

![iOS の画像](https://user-images.githubusercontent.com/836976/79284540-ec9cae80-7ef5-11ea-9eec-1da2302ac5a3.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- アイコン無し または 栃木県の形とか？

## 起こっている問題の再現手段 / Steps to Reproduce
1. iOS (Safari) で https://covid19-tochigi.netlify.com/ を開きお気に入り登録する

## 動作環境・ブラウザ / Environment
- iOS
- Safari

**Comment by y-ishida** [comment]
faviconを設定したけども、お気に入りのアイコンについてはまだ解決せず・・・

**Comment by Nekoya3** [comment]
nuxt.config.tsの
`
 { rel: 'apple-touch-icon', href: '/apple-touch-icon-precomposed.png' },
`
がiosでは利用されるためここを書き換えてください

**Comment by y-ishida** [comment]
既にそこは設定済みでpngファイルも置き換え済みなんですがうまく読み込まれないんですよね・・・。

https://github.com/covid19-tochigi/covid19/blob/668da6e3991e38ace90d80847a1a3ff07715d667/nuxt.config.ts#L82

デプロイ済み画像:
https://covid19-tochigi.netlify.app/apple-touch-icon-precomposed.png

**Comment by Nekoya3** [comment]
だとしたらiphone側のキツめのキャッシュが効いてるかもです。
別な端末とか他の方から見たときもそうだとしたら違いますが…

**Comment by y-ishida** [comment]
iphone側のキャッシュはキツめなんですね。iphone操作でキャッシュクリアしましたが効果なしでした。macを持っていないのでsafariをデバッグモードで見ることもできず、GETしに行っているのか、GETしに行っていなくてキャッシュを読んでるのか、間違ったURL読みに行っているのか全く判別できず・・・汗。
僕のと、もともと不具合見つけて頂いたyoshikosさんの端末はキャッシュがやられている？と思うので誰か試してほしいですー　泣

**Comment by y-ishida** [comment]
Slack 投稿より、ikutarom さんが別端末で確認したところ次のような動作だった。

> 自分のは、たぶん東京都のを一度見たことがあるからか？初めの数秒はイチョウか表示されて、その後栃木県のアイコンになりました。
> 上記現象は数回続けてやっても再現する。
> 栃木県も東京都のも、一度もアクセスしたことがないiphone 端末だと、はじめはSafariのマークで、数秒後に栃木県マークに。
> その後は繰り返すとすぐに栃木県マークが表示されます。

以上の動作より、自分の端末で解決していないのはおそらく iPhone のキャッシュの影響だと考えられる。よってサイト側の問題は解決していると思うので一旦クローズ。
