### ISSUE TITLE
OGP画像の作成

### ISSUE THREAD

**Issue by y-ishida** [covid19-tochigi/covid19#4]
## 改善詳細 / Details of Improvement
- OGP画像を作成していない＆設定していないので、SNS等で紹介されたときに、なんか寂しい。

## スクリーンショット / Screenshot

例えば、こういうの
![image](https://user-images.githubusercontent.com/836976/77839569-de8e2480-71b8-11ea-9499-f12b31907cdc.png)
とか、
![image](https://user-images.githubusercontent.com/836976/77839599-39278080-71b9-11ea-966b-534b28fd531f.png)
こういうのがあるいい感じ！

## 期待する見せ方・挙動 / Expected behavior
- まずは画像の作成が必要
- そのあとOGPメタデータ生成コード部分を復活させる

**Comment by hagume** [comment]
<img width="1058" alt="栃木県OGB画像イメージ" src="https://user-images.githubusercontent.com/62798392/77842286-801e7180-71cb-11ea-9f1e-4998cf6b3672.png">
パワポで画像を作ってみました、いかがですか？

**Comment by y-ishida** [comment]
ありがとうございます！　すごくいい感じです！　OGP画像に設定してみます。
