### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」の相談フローの改修

### ISSUE THREAD

**Issue by yoshikos** [covid19-tochigi/covid19#40]
## 改善詳細 / Details of Improvement
**24時間対応のコールセンターができたため、
相談フローの改修・相談先の情報更新を行う**

- 相談フローの変更
- 栃木県新型コロナウイルスコールセンター(24時間対応) ※4月16日開設 の情報更新を行う
- 外国語対応の相談窓口の情報更新を行う
- 聴覚障害者向けの相談窓口の情報更新を行う

新型コロナウイルス感染症に関する電話相談窓口について
http://www.pref.tochigi.lg.jp/e04/welfare/hoken-eisei/kansen/hp/shingatakoronavirussoudannmadoguti.html

新フロー図掲載の会議資料
http://www.pref.tochigi.lg.jp/e04/welfare/hoken-eisei/kansen/hp/documents/20200415honbukaigi.pdf

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/61943978/79558804-bb7fd200-80df-11ea-8cce-18aa7af5100f.png)

![3936B8E7-9B81-4AB4-9E91-0C8378DCBAA7](https://user-images.githubusercontent.com/61943978/80225790-84349680-8686-11ea-95bb-1e952098348c.jpeg)

## 期待する見せ方・挙動 / Expected behavior
-  「新型コロナウイルス感染症が心配なときに」の該当箇所の修正を行う

コールセンター開設により、対応フロー変更
①一時受付が、全て24時間対応のコールセンター(栃木県、外国人向けの2種)に集約
※聴覚障害者は、FAXで連絡
※管轄ごとへの連絡は不要となった
②必要に応じて、コールセンターから帰国者・接触者相談センターへ紹介

尚、厚生労働省の電話相談窓口は、これまで通り。
栃木県民は、栃木県のコールセンターに相談するか、
厚生労働省の電話相談窓口を利用する事ができる。
(参考)
 ◆ 厚生労働省においても、午前9時から午後9時まで（土日・祝日も実施）新型コロナウイルス感染症に関する相談窓口を設置しています。
   厚生労働省の電話相談窓口　ＴＥＬ　０１２０－５６５６５３（フリーダイヤル）

**相談窓口１【健常者向け】**
栃木県新型コロナウイルスコールセンターの開設について
http://www.pref.tochigi.lg.jp/e04/houdou/200415koronakorusenta.html

**相談窓口２【海外の方向け】※多言語対応窓口　24時間18言語対応**
栃木県に住む外国人のための新型コロナウイルス相談ホットライン
http://tia21.or.jp/content/files/info/coronavirushotline.pdf
とちぎ外国人相談がいこくじんそうだんサポートセンター
http://tia21.or.jp/hello.html

**相談窓口３【視覚障害者向け】**
聴覚等に障害のある方で、電話での御相談が難しい方はFAX相談票に相談内容を記載の上、下記の番号までFAXを送信ください。

◆FAX相談票（聴覚障害等のある方の相談用）
http://www.pref.tochigi.lg.jp/e04/welfare/hoken-eisei/kansen/hp/documents/soudanhyou_shusei.pdf
◎平日　午前8時30分～午後8時00分：FAX ０２８－６２３－３０５２
◎平日　午後8時00分～午前8時30分・休日 ：FAX ０２８－６２３－２５２７

**Comment by hagume** [comment]
flow update #57
で対応ずみ！
