### ISSUE TITLE
症状の重度の別は記載しない方が良い

### ISSUE THREAD

**Issue by y-ishida** [covid19-tochigi/covid19#49]
## 改善詳細 / Details of Improvement
- 「軽症・中等症」と「重症」の別は明確に栃木県から公表されていないが、サイトの表記は分かれている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/836976/80160084-a935f480-8607-11ea-8c09-97079aabe777.png)

## 期待する見せ方・挙動 / Expected behavior
- 症状の重度の別は表記せず「入院患者」としてだけ表記する形にする
- 県には公開の旨申し入れ済み

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hagume** [comment]
サイトのグラフの見た目の修正 #56
で対応ずみ！
