### ISSUE TITLE
検査実施数と電話相談件数が栃木県から発表されなくなったかもしれない

### ISSUE THREAD

**Issue by y-ishida** [covid19-tochigi/covid19#5]
## 改善詳細 / Details of Improvement
- 検査実施数と電話相談件数が栃木県から発表されなくなったかもしれない
- いつもは[栃木県新型コロナウイルス感染症対策本部会議](http://www.pref.tochigi.lg.jp/e04/welfare/hoken-eisei/kansen/hp/shingatacoronataisakuhonbu.html) の資料から値を拾ってきていたが、[3/26 の会議資料](http://www.pref.tochigi.lg.jp/e04/welfare/hoken-eisei/kansen/hp/documents/20200326honbusiryo.pdf) からは、これらの値の表が削除されていた 
- 県に対して何らかのアクションをとるべきか、、、？

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/836976/77839726-37aa8800-71ba-11ea-9b1e-37a10d386bbb.png)

## 期待する見せ方・挙動 / Expected behavior
- 今、増えているのか、収束しそうなのかということがグラフで見て分かるのは重要なのなので、ぜひこのデータは取得したいところ

**Comment by hagume** [comment]
栃木県の健康増進課（028-623-3089)にコンタクトしました。
回答：3.26日分は作業が追いついてないため、掲載できなかった。今後も掲載予定。

**Comment by y-ishida** [comment]
今後も掲載予定とのことで、本件は一旦クローズしましょう
