### ISSUE TITLE
埋め込みコードでグラフをSNSに投稿すると画像が東京都のもので表示される

### ISSUE THREAD

**Issue by yoshikos** [covid19-tochigi/covid19#50]
## 起こっている問題 / The Problem
- 埋め込みコードでグラフを引用し、SNSに投稿すると、画像が東京都のもので表示される

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/61943978/80165206-ed2ff600-8615-11ea-99fc-332eb268a77a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 栃木県の該当グラフの画像が表示されるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. グラフ右下の埋め込みコードを利用し、SNSへ投稿する
2. 投稿内容のグラフ画像が、東京都のものになっているか確認する

**Comment by Nekoya3** [comment]
OGPBuilder.pyが正常に動作するように設定すればOKです

**Comment by mira-tech** [comment]
横から失礼します
スクリプトの問題じゃなくて`/pages/cards/_card.vue`の中でわざわざ本家の方を取りに行く記述してますね

修正したプルリク投げます！

**Comment by y-ishida** [comment]
すみません、いきおいでマージしてしまいましたが、ちょっと master へ push する内容が問題があるように思うので一旦 revert させて頂きました。
#82 ← こちらを参照

**Comment by mira-tech** [comment]
確かに一回cloneしてその中のファイル内に生成したOGP画像をpushしないと全部消えちゃいますね...また修正するプルリク投げますね🙇‍♂️

**Comment by y-ishida** [comment]
マージする前にちゃんとレビューすれば良かったですね・・・すみません、お手数おかけしますがよろしくお願いします！

**Comment by y-ishida** [comment]
https://github.com/covid19-tochigi/covid19/pull/81#pullrequestreview-468108897
ここにも少しコメントしておきました！
